[package]
name = "print-banner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.11"
rand = "0.8.5"
serde_json = "1.0.108"
regex = "1.10.2"
