#!/usr/bin/env bash

# Function to display usage information
usage() {
  echo "usage: $0 <directory> [--cleanup]"
  exit 1
}

# Check if at least one argument is passed
[ $# -lt 1 ] && usage

# Initialize variables
directory=""
cleanup=false

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --cleanup)
      cleanup=true
      shift
      ;;
    *)
      directory="$1"
      shift
      ;;
  esac
done

# Ensure a directory is provided
[ -z "$directory" ] && usage

# Function to convert audio files to MP3
convert_to_mp3() {
  find "$directory" -type f -regextype posix-extended -regex ".*\.$1$" -exec sh -c 'ffmpeg -y -i "$0" -b:a 320k -map_metadata 0 -id3v2_version 3 "${0%.$1}.mp3"' {} \;
}

# Array of file extensions to convert
extensions=("flac" "m4a" "wav")

# Loop through the array and convert each extension to MP3
for ext in "${extensions[@]}"; do
  convert_to_mp3 "$ext"
done

# Remove non-MP3 files if they don't have a double extension
for ext in "${extensions[@]}"; do
  find "$directory" -type f -regextype posix-extended -regex ".*\.$ext$" ! -name "*.mp3" -exec rm {} \;
done

# Conditional cleanup
if [ "$cleanup" = true ]; then
  find "$directory" -type f -regextype posix-extended ! -regex ".*\.(mp3|zip|tar|gz|bz2|7z|rar)$" -exec rm {} \;
  find "$directory" -type d -empty -delete
fi
