#!/usr/bin/env bash
# Script to list and summarize directories

# Colors
DIR_COLOR='\e[93;1m'
FILE_COLOR='\e[96;1m'
TOTAL_COLOR='\e[95;1m' 
RESET_COLOR='\e[0m'

print_listings() {
    local type="$1"
    sudo find . -maxdepth 1 -not -name '.' -type "$type" -exec sh -c 'du -sh "${1#./}"' _ {} \;
}

get_count() {
    local type="$1"
    sudo find . -maxdepth 1 -not -name '.' -type "$type" | wc -l
}

# Directories
echo -en "${DIR_COLOR}"
total_dirs=$(get_count d)
if [ "$total_dirs" -gt 0 ]; then
    print_listings d | sort -hr
else
    echo "No directories found."
fi
echo -en "${RESET_COLOR}"

# Files
echo "~~~"
echo -en "${FILE_COLOR}"
total_files=$(get_count f)
if [ "$total_files" -gt 0 ]; then
    print_listings f  | sort -hr
else
    echo "No files found."
fi
echo -en "${RESET_COLOR}"

# Totals
total_size=$(sudo du -shc | awk 'NR>1 {print $1}')

echo "~~~"
echo -en "${TOTAL_COLOR}"
echo "Total Files: $total_files"
echo "Total Directories: $total_dirs"
echo "Total Size: $total_size"
echo -en "${RESET_COLOR}"
