#!/usr/bin/env bash
# LSD - List and Summarize Directories

# Colors
DIR_COLOR='\e[93;1m'    # Bright Magenta
FILE_COLOR='\e[96;1m'   # Bright Cyan
TOTAL_COLOR='\e[95;1m'  # Bright Yellow
RESET_COLOR='\e[0m'

# Directories
echo -en "${DIR_COLOR}"
du -sh ./*/ | sed 's:/$::' | sort -hr 
echo -en "${RESET_COLOR}"

# Files
echo "~~~"
echo -en "${FILE_COLOR}"
find . -maxdepth 1 -type f -exec sh -c 'du -sh "${1#./}"' _ {} \; | sort -hr
echo -en "${RESET_COLOR}"

# Totals
total_files=$(find . -maxdepth 1 -type f | wc -l)
total_dirs=$(find . -maxdepth 1 -type d | wc -l)
total_size=$(du -shc | awk 'NR>1 {print $1}')

echo "~~~"
echo -en "${TOTAL_COLOR}"
echo "Total Files: $total_files"
echo "Total Directories: $total_dirs"
echo "Total Size: $total_size"
echo -en "${RESET_COLOR}"
