#!/usr/bin/env bash
# Monitor a file existence

TARGET="$1"
#NOTIFICATION_SOUND="/path/to/notification_sound.wav"

if [[ -z "$TARGET" ]]; then
    echo "usage: monitor <URL or local filepath>"
    exit 1
fi

check_remote() {
    curl -s --head "$1" | head -n 1 | grep "HTTP/1.[01] [23]" > /dev/null
    return $?
}

check_local() {
    [[ -f "$1" ]]
    return $?
}

while true; do
    if [[ "$TARGET" == http* ]]; then
        check_remote "$TARGET"
    else
        check_local "$TARGET"
    fi

    if [ $? -eq 0 ]; then
        notify-send "Notification" "The target $TARGET is now available."
        #paplay "$NOTIFICATION_SOUND"
        exit 0
    fi
    sleep 1
done
