#!/usr/bin/env bash
# Script to add output prefix to the command output with color
# https://superuser.com/a/453609

RED='\033[0;31m'
GREEN='\033[0;32m'
RESET='\033[0m'

{
  {
    "$@"
  } 2>&3 | sed "s/^/$(echo -e "${GREEN}STDOUT:${RESET}") /"
} 3>&1 1>&2 | sed "s/^/$(echo -e "${RED}STDERR:${RESET}") /"
