#!/usr/bin/env bash
# Script for grepping recursively from '.txt.zst' files

# Check arguments
if [ $# -ne 2 ]; then
  echo "Usage: $0 <regex> <directory>"
  exit 1
fi

pattern="$1"
directory="$2"

# Validate directory
if [ ! -d "$directory" ]; then
  echo "Directory $directory does not exist."
  exit 1
fi

# Main
find "$directory" -iname '*.zst' -type f -print0 | parallel --bar -n1 -j1 -0 "zstdgrep -Ehis -- '$pattern' {}"